sql:
  history: history.sql
  growth: sql/growth.sql
  peGrowth: peGrowth.sql
  stockList: /stockList.sql
  industrySQL: sql/industry.sql
  industrySQL2: sql/industry2.sql
  peSQL: sql/pe.sql
path:
  default-kLine: 选股\kLine
db: mysql+pymysql://root:root@localhost:3306/stock
constant_variables:
    low_ferquency_update_days: 7
