sql:
  history: history.sql
  growth: sql/growth.sql
  peGrowth: peGrowth.sql
  stockList: /stockList.sql

path:
  default-kLine: D:\onedrive\OneDrive - ncist.edu.cn\选股\kLine
db: mysql+pymysql://root:root@localhost:3306/stock

